// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gheecokmulrlxzgahyrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoZWVjb2ttdWxybHh6Z2FoeXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjU2MDMsImV4cCI6MjA2OTQwMTYwM30.0_YCaCa9P_QLlb3TWm51iJFXaDl3cKsaqqFalEeaLPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});